apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app: search
spec:
  ports:
    # the port that this service should serve on
  - port: 9200
    targetPort: 9200
  selector:
    app: search

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: elasticsearch:2.4
        env:
        ports:
          - containerPort: 9200
